export interface ResultDto {
  nome: string;
  email: string;
  telefone: string;
  questao_1_grupo_1_Placas_e_Parafusos_para_quadril_ou_pelvis: boolean
  questao_1_grupo_1_Placas_e_Parafusos_extremidades_inferiores: boolean
  questao_1_grupo_1_Placas_e_Parafusos_extremidades_superiores: boolean
  questao_1_grupo_2_Pinos_intramedulares_acetabular: boolean
  questao_1_grupo_2_Pinos_intramedulares_femoral: boolean
  questao_1_grupo_2_Pinos_intramedulares_tibiais: boolean
  questao_1_grupo_3_Parafusos_pequenos_e_canulados: boolean
  questao_1_grupo_3_Parafusos_grandes_e_canulados: boolean
  questao_1_grupo_4_Pinos_intramedulares_femoral: boolean
  questao_1_grupo_4_Fixacao_externa_media: boolean
  questao_1_grupo_4_Pequena_fixacao_externa: boolean
  questao_1_grupo_4_Mini_fixacao_externa: boolean
  questao_1_pergunta_2: string
  questao_1_pergunta_3_SP: string
  questao_1_pergunta_3_RJ: string
  questao_1_pergunta_3_MG: string
  questao_1_pergunta_3_RECIFE: string
  questao_1_pergunta_3_FORTALEZA: string
  questao_1_pergunta_3_OUTROS: string
  questao_1_pergunta_4_qtd_publico: string
  questao_1_pergunta_4_qtd_privado: string
  questao_2_PlacasParaQuadrilPelvis_1: boolean
  questao_2_PlacasParaQuadrilPelvis_2: string
  questao_2_PlacasParaQuadrilPelvis_3: string
  questao_2_PlacasParaQuadrilPelvis_4: string
  questao_2_PlacasExtremidadesInferiores_1: boolean
  questao_2_PlacasExtremidadesInferiores_2: string
  questao_2_PlacasExtremidadesInferiores_3: string
  questao_2_PlacasExtremidadesInferiores_4: string
  questao_2_PlacasExtremidadesSuperiores_1: boolean
  questao_2_PlacasExtremidadesSuperiores_2: string
  questao_2_PlacasExtremidadesSuperiores_3: string
  questao_2_PlacasExtremidadesSuperiores_4: string
  questao_2_ParafusosQuadrilPelvis_1: boolean
  questao_2_ParafusosQuadrilPelvis_2: string
  questao_2_ParafusosQuadrilPelvis_3: string
  questao_2_ParafusosQuadrilPelvis_4: string
  questao_2_ParafusosExtremidadesInferiores_1: boolean
  questao_2_ParafusosExtremidadesInferiores_2: string
  questao_2_ParafusosExtremidadesInferiores_3: string
  questao_2_ParafusosExtremidadesInferiores_4: string
  questao_2_ParafusosExtremidadesSuperiores_1: boolean
  questao_2_ParafusosExtremidadesSuperiores_2: string
  questao_2_ParafusosExtremidadesSuperiores_3: string
  questao_2_ParafusosExtremidadesSuperiores_4: string
  questao_2_PinosIntramedularesUmeral_1: boolean
  questao_2_PinosIntramedularesUmeral_2: string
  questao_2_PinosIntramedularesUmeral_3: string
  questao_2_PinosIntramedularesUmeral_4: string
  questao_2_PinosIntramedularesAcetabulares_1: boolean
  questao_2_PinosIntramedularesAcetabulares_2: string
  questao_2_PinosIntramedularesAcetabulares_3: string
  questao_2_PinosIntramedularesAcetabulares_4: string
  questao_2_PinoIntramedularFemoral_1: boolean
  questao_2_PinoIntramedularFemoral_2: string
  questao_2_PinoIntramedularFemoral_3: string
  questao_2_PinoIntramedularFemoral_4: string
  questao_2_PinosIntramedularesTibiais_1: boolean
  questao_2_PinosIntramedularesTibiais_2: string
  questao_2_PinosIntramedularesTibiais_3: string
  questao_2_PinosIntramedularesTibiais_4: string
  questao_2_ParafusosPequenosCanulados_1: boolean
  questao_2_ParafusosPequenosCanulados_2: string
  questao_2_ParafusosPequenosCanulados_3: string
  questao_2_ParafusosPequenosCanulados_4: string
  questao_2_ParafusosGrandescanulados_1: boolean
  questao_2_ParafusosGrandescanulados_2: string
  questao_2_ParafusosGrandescanulados_3: string
  questao_2_ParafusosGrandescanulados_4: string
  questao_2_GrandesFixaCoesExternas_1: boolean
  questao_2_GrandesFixaCoesExternas_2: string
  questao_2_GrandesFixaCoesExternas_3: string
  questao_2_GrandesFixaCoesExternas_4: string
  questao_2_FixacoesExternasMedias_1: boolean
  questao_2_FixacoesExternasMedias_2: string
  questao_2_FixacoesExternasMedias_3: string
  questao_2_FixacoesExternasMedias_4: string
  questao_2_PequenasFixaCoesExternas_1: boolean
  questao_2_PequenasFixaCoesExternas_2: string
  questao_2_PequenasFixaCoesExternas_3: string
  questao_2_PequenasFixaCoesExternas_4: string
  questao_2_MiniFixacoesExternas_1: boolean
  questao_2_MiniFixacoesExternas_2: string
  questao_2_MiniFixacoesExternas_3: string
  questao_2_MiniFixacoesExternas_4: string
  questao_3_PlacasParaQuadrilPelvis_1: boolean
  questao_3_PlacasParaQuadrilPelvis_2: string
  questao_3_PlacasParaQuadrilPelvis_3: string
  questao_3_PlacasExtremidadesInferiores_1: boolean
  questao_3_PlacasExtremidadesInferiores_2: string
  questao_3_PlacasExtremidadesInferiores_3: string
  questao_3_PlacasExtremidadesSuperiores_1: boolean
  questao_3_PlacasExtremidadesSuperiores_2: string
  questao_3_PlacasExtremidadesSuperiores_3: string
  questao_3_ParafusosQuadrilPelvis_1: boolean
  questao_3_ParafusosQuadrilPelvis_2: string
  questao_3_ParafusosQuadrilPelvis_3: string
  questao_3_ParafusosExtremidadesInferiores_1: boolean
  questao_3_ParafusosExtremidadesInferiores_2: string
  questao_3_ParafusosExtremidadesInferiores_3: string
  questao_3_ParafusosExtremidadesSuperiores_1: boolean
  questao_3_ParafusosExtremidadesSuperiores_2: string
  questao_3_ParafusosExtremidadesSuperiores_3: string
  questao_3_PinosIntramedularesUmeral_1: boolean
  questao_3_PinosIntramedularesUmeral_2: string
  questao_3_PinosIntramedularesUmeral_3: string
  questao_3_PinosIntramedularesAcetabulares_1: boolean
  questao_3_PinosIntramedularesAcetabulares_2: string
  questao_3_PinosIntramedularesAcetabulares_3: string
  questao_3_PinoIntramedularFemoral_1: boolean
  questao_3_PinoIntramedularFemoral_2: string
  questao_3_PinoIntramedularFemoral_3: string
  questao_3_PinosIntramedularesTibiais_1: boolean
  questao_3_PinosIntramedularesTibiais_2: string
  questao_3_PinosIntramedularesTibiais_3: string
  questao_3_ParafusosPequenosCanulados_1: boolean
  questao_3_ParafusosPequenosCanulados_2: string
  questao_3_ParafusosPequenosCanulados_3: string
  questao_3_ParafusosGrandescanulados_1: boolean
  questao_3_ParafusosGrandescanulados_2: string
  questao_3_ParafusosGrandescanulados_3: string
  questao_3_GrandesFixaCoesExternas_1: boolean
  questao_3_GrandesFixaCoesExternas_2: string
  questao_3_GrandesFixaCoesExternas_3: string
  questao_3_FixacoesExternasMedias_1: boolean
  questao_3_FixacoesExternasMedias_2: string
  questao_3_FixacoesExternasMedias_3: string
  questao_3_PequenasFixaCoesExternas_1: boolean
  questao_3_PequenasFixaCoesExternas_2: string
  questao_3_PequenasFixaCoesExternas_3: string
  questao_3_MiniFixacoesExternas_1: boolean
  questao_3_MiniFixacoesExternas_2: string
  questao_3_MiniFixacoesExternas_3: string
  questao_4: string
  questao_5: string
  questao_5_pergunta_1: string
  questao_5_pergunta_2: string
  questao_5_pergunta_3: string
  questao_6_PlacasParaQuadrilPelvis_2: string
  questao_6_PlacasParaQuadrilPelvis_3: string
  questao_6_PlacasParaQuadrilPelvis_4: string
  questao_6_PlacasParaQuadrilPelvis_5: string
  questao_6_PlacasParaQuadrilPelvis_6: string
  questao_6_PlacasParaQuadrilPelvis_7: string
  questao_6_PlacasParaQuadrilPelvis_8: string
  questao_6_PlacasParaQuadrilPelvis_9: string
  questao_6PlacasExtremidadesInferiores_2: string
  questao_6PlacasExtremidadesInferiores_3: string
  questao_6PlacasExtremidadesInferiores_4: string
  questao_6PlacasExtremidadesInferiores_5: string
  questao_6PlacasExtremidadesInferiores_6: string
  questao_6PlacasExtremidadesInferiores_7: string
  questao_6PlacasExtremidadesInferiores_8: string
  questao_6PlacasExtremidadesInferiores_9: string
  questao_6_PlacasExtremidadesSuperiores_2: string
  questao_6_PlacasExtremidadesSuperiores_3: string
  questao_6_PlacasExtremidadesSuperiores_4: string
  questao_6_PlacasExtremidadesSuperiores_5: string
  questao_6_PlacasExtremidadesSuperiores_6: string
  questao_6_PlacasExtremidadesSuperiores_7: string
  questao_6_PlacasExtremidadesSuperiores_8: string
  questao_6_PlacasExtremidadesSuperiores_9: string
  questao_6_ParafusosQuadrilPelvis_2: string
  questao_6_ParafusosQuadrilPelvis_3: string
  questao_6_ParafusosQuadrilPelvis_4: string
  questao_6_ParafusosQuadrilPelvis_5: string
  questao_6_ParafusosQuadrilPelvis_6: string
  questao_6_ParafusosQuadrilPelvis_7: string
  questao_6_ParafusosQuadrilPelvis_8: string
  questao_6_ParafusosQuadrilPelvis_9: string
  questao_6_ParafusosExtremidadesInferiores_2: string
  questao_6_ParafusosExtremidadesInferiores_3: string
  questao_6_ParafusosExtremidadesInferiores_4: string
  questao_6_ParafusosExtremidadesInferiores_5: string
  questao_6_ParafusosExtremidadesInferiores_6: string
  questao_6_ParafusosExtremidadesInferiores_7: string
  questao_6_ParafusosExtremidadesInferiores_8: string
  questao_6_ParafusosExtremidadesInferiores_9: string
  questao_6_ParafusosExtremidadesSuperiores_2: string
  questao_6_ParafusosExtremidadesSuperiores_3: string
  questao_6_ParafusosExtremidadesSuperiores_4: string
  questao_6_ParafusosExtremidadesSuperiores_5: string
  questao_6_ParafusosExtremidadesSuperiores_6: string
  questao_6_ParafusosExtremidadesSuperiores_7: string
  questao_6_ParafusosExtremidadesSuperiores_8: string
  questao_6_ParafusosExtremidadesSuperiores_9: string
  questao_6_PinosIntramedularesUmeral_2: string
  questao_6_PinosIntramedularesUmeral_3: string
  questao_6_PinosIntramedularesUmeral_4: string
  questao_6_PinosIntramedularesUmeral_5: string
  questao_6_PinosIntramedularesUmeral_6: string
  questao_6_PinosIntramedularesUmeral_7: string
  questao_6_PinosIntramedularesUmeral_8: string
  questao_6_PinosIntramedularesUmeral_9: string
  questao_6_PinosIntramedularesAcetabulares_2: string
  questao_6_PinosIntramedularesAcetabulares_3: string
  questao_6_PinosIntramedularesAcetabulares_4: string
  questao_6_PinosIntramedularesAcetabulares_5: string
  questao_6_PinosIntramedularesAcetabulares_6: string
  questao_6_PinosIntramedularesAcetabulares_7: string
  questao_6_PinosIntramedularesAcetabulares_8: string
  questao_6_PinosIntramedularesAcetabulares_9: string
  questao_6_PinoIntramedularFemoral_2: string
  questao_6_PinoIntramedularFemoral_3: string
  questao_6_PinoIntramedularFemoral_4: string
  questao_6_PinoIntramedularFemoral_5: string
  questao_6_PinoIntramedularFemoral_6: string
  questao_6_PinoIntramedularFemoral_7: string
  questao_6_PinoIntramedularFemoral_8: string
  questao_6_PinoIntramedularFemoral_9: string
  questao_6_PinosIntramedularesTibiais_2: string
  questao_6_PinosIntramedularesTibiais_3: string
  questao_6_PinosIntramedularesTibiais_4: string
  questao_6_PinosIntramedularesTibiais_5: string
  questao_6_PinosIntramedularesTibiais_6: string
  questao_6_PinosIntramedularesTibiais_7: string
  questao_6_PinosIntramedularesTibiais_8: string
  questao_6_PinosIntramedularesTibiais_9: string
  questao_6_ParafusosPequenosCanulados_2: string
  questao_6_ParafusosPequenosCanulados_3: string
  questao_6_ParafusosPequenosCanulados_4: string
  questao_6_ParafusosPequenosCanulados_5: string
  questao_6_ParafusosPequenosCanulados_6: string
  questao_6_ParafusosPequenosCanulados_7: string
  questao_6_ParafusosPequenosCanulados_8: string
  questao_6_ParafusosPequenosCanulados_9: string
  questao_6_ParafusosGrandescanulados_2: string
  questao_6_ParafusosGrandescanulados_3: string
  questao_6_ParafusosGrandescanulados_4: string
  questao_6_ParafusosGrandescanulados_5: string
  questao_6_ParafusosGrandescanulados_6: string
  questao_6_ParafusosGrandescanulados_7: string
  questao_6_ParafusosGrandescanulados_8: string
  questao_6_ParafusosGrandescanulados_9: string
  questao_6_GrandesFixaCoesExternas_2: string
  questao_6_GrandesFixaCoesExternas_3: string
  questao_6_GrandesFixaCoesExternas_4: string
  questao_6_GrandesFixaCoesExternas_5: string
  questao_6_GrandesFixaCoesExternas_6: string
  questao_6_GrandesFixaCoesExternas_7: string
  questao_6_GrandesFixaCoesExternas_8: string
  questao_6_GrandesFixaCoesExternas_9: string
  questao_6_FixacoesExternasMedias_2: string
  questao_6_FixacoesExternasMedias_3: string
  questao_6_FixacoesExternasMedias_4: string
  questao_6_FixacoesExternasMedias_5: string
  questao_6_FixacoesExternasMedias_6: string
  questao_6_FixacoesExternasMedias_7: string
  questao_6_FixacoesExternasMedias_8: string
  questao_6_FixacoesExternasMedias_9: string
  questao_6_PequenasFixaCoesExternas_2: string
  questao_6_PequenasFixaCoesExternas_3: string
  questao_6_PequenasFixaCoesExternas_4: string
  questao_6_PequenasFixaCoesExternas_5: string
  questao_6_PequenasFixaCoesExternas_6: string
  questao_6_PequenasFixaCoesExternas_7: string
  questao_6_PequenasFixaCoesExternas_8: string
  questao_6_PequenasFixaCoesExternas_9: string
  questao_6_MiniFixacoesExternas_2: string
  questao_6_MiniFixacoesExternas_3: string
  questao_6_MiniFixacoesExternas_4: string
  questao_6_MiniFixacoesExternas_5: string
  questao_6_MiniFixacoesExternas_6: string
  questao_6_MiniFixacoesExternas_7: string
  questao_6_MiniFixacoesExternas_8: string
  questao_6_MiniFixacoesExternas_9: string
  questao_7: string;
  questao_8: string;
  questao_8_1: string;
  questao_8_2: string;
  questao_8_3_1: string;
  questao_8_3_2: string;
  questao_8_3_3: string;
  questao_8_3_4: string;
  questao_9: string;
  questao_10: string;
  questao_10_1: string;
  questao_10_2: string;
  questao_10_3: string;
  questao_10_4: string;
  comentario_pesquisa: string;
  recomendacoes: string;
}

