export interface ResponsesHospitalTraumaDTO {
  cargo: string
  email: string
  empresa: string
  nome: string
  questao_1_grupo_1_Placas_e_Parafusos_extremidades_inferiores: boolean
  questao_1_grupo_1_Placas_e_Parafusos_extremidades_superiores: boolean
  questao_1_grupo_1_Placas_e_Parafusos_para_quadril_ou_pelvis: boolean
  questao_1_grupo_2_Pinos_intramedulares_acetabular: boolean
  questao_1_grupo_2_Pinos_intramedulares_femoral: boolean
  questao_1_grupo_2_Pinos_intramedulares_tibiais: boolean
  questao_1_grupo_3_Parafusos_grandes_e_canulados: boolean
  questao_1_grupo_3_Parafusos_pequenos_e_canulados: boolean
  questao_1_grupo_4_Fixacao_externa_media: boolean
  questao_1_grupo_4_Mini_fixacao_externa: boolean
  questao_1_grupo_4_Pequena_fixacao_externa: boolean
  questao_1_grupo_4_Pinos_intramedulares_femoral: boolean
  questao_2_1: boolean
  questao_2_2: boolean
  questao_2_3: boolean
  questao_3: string
  questao_4: string
  questao_5_Fixacoes_externas_medias_1: boolean
  questao_5_Fixacoes_externas_medias_2: string
  questao_5_Fixacoes_externas_medias_3: string
  questao_5_Fixacoes_externas_medias_4: string
  questao_5_Grandes_Fixacoes_Externas_1: boolean
  questao_5_Grandes_Fixacoes_Externas_2: string
  questao_5_Grandes_Fixacoes_Externas_3: string
  questao_5_Grandes_Fixacoes_Externas_4: string
  questao_5_Mini_Fixacoes_Externas_1: boolean
  questao_5_Mini_Fixacoes_Externas_2: string
  questao_5_Mini_Fixacoes_Externas_3: string
  questao_5_Mini_Fixacoes_Externas_4: string
  questao_5_Parafusos_extremidades_inferiores_1: boolean
  questao_5_Parafusos_extremidades_inferiores_2: string
  questao_5_Parafusos_extremidades_inferiores_3: string
  questao_5_Parafusos_extremidades_inferiores_4: string
  questao_5_Parafusos_extremidades_superiores_1: boolean
  questao_5_Parafusos_extremidades_superiores_2: string
  questao_5_Parafusos_extremidades_superiores_3: string
  questao_5_Parafusos_extremidades_superiores_4: string
  questao_5_Parafusos_grandes_e_canulados_1: boolean
  questao_5_Parafusos_grandes_e_canulados_2: string
  questao_5_Parafusos_grandes_e_canulados_3: string
  questao_5_Parafusos_grandes_e_canulados_4: string
  questao_5_Parafusos_para_quadril_ou_pelvis_1: boolean
  questao_5_Parafusos_para_quadril_ou_pelvis_2: string
  questao_5_Parafusos_para_quadril_ou_pelvis_3: string
  questao_5_Parafusos_para_quadril_ou_pelvis_4: string
  questao_5_Parafusos_pequenos_e_canulados_1: boolean
  questao_5_Parafusos_pequenos_e_canulados_2: string
  questao_5_Parafusos_pequenos_e_canulados_3: string
  questao_5_Parafusos_pequenos_e_canulados_4: string
  questao_5_Pequenas_Fixacoes_Externas_1: boolean
  questao_5_Pequenas_Fixacoes_Externas_2: string
  questao_5_Pequenas_Fixacoes_Externas_3: string
  questao_5_Pequenas_Fixacoes_Externas_4: string
  questao_5_Pino_intramedular_femoral_1: boolean
  questao_5_Pino_intramedular_femoral_2: string
  questao_5_Pino_intramedular_femoral_3: string
  questao_5_Pino_intramedular_femoral_4: string
  questao_5_Pinos_intramedulares_acetabulares_1: boolean
  questao_5_Pinos_intramedulares_acetabulares_2: string
  questao_5_Pinos_intramedulares_acetabulares_3: string
  questao_5_Pinos_intramedulares_acetabulares_4: string
  questao_5_Pinos_intramedulares_tibiais_1: boolean
  questao_5_Pinos_intramedulares_tibiais_2: string
  questao_5_Pinos_intramedulares_tibiais_3: string
  questao_5_Pinos_intramedulares_tibiais_4: string
  questao_5_Pinos_intramedulares_umeral_1: boolean
  questao_5_Pinos_intramedulares_umeral_2: string
  questao_5_Pinos_intramedulares_umeral_3: string
  questao_5_Pinos_intramedulares_umeral_4: string
  questao_5_Placas_extremidades_inferiores_1: boolean
  questao_5_Placas_extremidades_inferiores_2: string
  questao_5_Placas_extremidades_inferiores_3: string
  questao_5_Placas_extremidades_inferiores_4: string
  questao_5_Placas_extremidades_superiores_1: boolean
  questao_5_Placas_extremidades_superiores_2: string
  questao_5_Placas_extremidades_superiores_3: string
  questao_5_Placas_extremidades_superiores_4: string
  questao_5_Placas_para_quadril_ou_pelvis_1: boolean
  questao_5_Placas_para_quadril_ou_pelvis_2: string
  questao_5_Placas_para_quadril_ou_pelvis_3: string
  questao_5_Placas_para_quadril_ou_pelvis_4: string
  questao_6_Fixacoes_externas_medias_1: boolean
  questao_6_Fixacoes_externas_medias_2: string
  questao_6_Fixacoes_externas_medias_3: string
  questao_6_Grandes_Fixacoes_Externas_1: boolean
  questao_6_Grandes_Fixacoes_Externas_2: string
  questao_6_Grandes_Fixacoes_Externas_3: string
  questao_6_Mini_Fixacoes_Externas_1: boolean
  questao_6_Mini_Fixacoes_Externas_2: string
  questao_6_Mini_Fixacoes_Externas_3: string
  questao_6_Parafusos_extremidades_inferiores_1: boolean
  questao_6_Parafusos_extremidades_inferiores_2: string
  questao_6_Parafusos_extremidades_inferiores_3: string
  questao_6_Parafusos_extremidades_superiores_1: boolean
  questao_6_Parafusos_extremidades_superiores_2: string
  questao_6_Parafusos_extremidades_superiores_3: string
  questao_6_Parafusos_grandes_e_canulados_1: boolean
  questao_6_Parafusos_grandes_e_canulados_2: string
  questao_6_Parafusos_grandes_e_canulados_3: string
  questao_6_Parafusos_para_quadril_ou_pelvis_1: boolean
  questao_6_Parafusos_para_quadril_ou_pelvis_2: string
  questao_6_Parafusos_para_quadril_ou_pelvis_3: string
  questao_6_Parafusos_pequenos_e_canulados_1: boolean
  questao_6_Parafusos_pequenos_e_canulados_2: string
  questao_6_Parafusos_pequenos_e_canulados_3: string
  questao_6_Pequenas_Fixacoes_Externas_1: boolean
  questao_6_Pequenas_Fixacoes_Externas_2: string
  questao_6_Pequenas_Fixacoes_Externas_3: string
  questao_6_Pino_intramedular_femoral_1: boolean
  questao_6_Pino_intramedular_femoral_2: string
  questao_6_Pino_intramedular_femoral_3: string
  questao_6_Pinos_intramedulares_acetabulares_1: boolean
  questao_6_Pinos_intramedulares_acetabulares_2: string
  questao_6_Pinos_intramedulares_acetabulares_3: string
  questao_6_Pinos_intramedulares_tibiais_1: boolean
  questao_6_Pinos_intramedulares_tibiais_2: string
  questao_6_Pinos_intramedulares_tibiais_3: string
  questao_6_Pinos_intramedulares_umeral_1: boolean
  questao_6_Pinos_intramedulares_umeral_2: string
  questao_6_Pinos_intramedulares_umeral_3: string
  questao_6_Placas_extremidades_inferiores_1: boolean
  questao_6_Placas_extremidades_inferiores_2: string
  questao_6_Placas_extremidades_inferiores_3: string
  questao_6_Placas_extremidades_superiores_1: boolean
  questao_6_Placas_extremidades_superiores_2: string
  questao_6_Placas_extremidades_superiores_3: string
  questao_6_Placas_para_quadril_ou_pelvis_1: boolean
  questao_6_Placas_para_quadril_ou_pelvis_2: string
  questao_6_Placas_para_quadril_ou_pelvis_3: string
  questao_7: string
  questao_8: string
  questao_8_1: string
  questao_8_2: string
  questao_8_3: string
  questao_9_Fixacao_externa_media_1: boolean
  questao_9_Fixacao_externa_media_2: string
  questao_9_Fixacao_externa_media_3: string
  questao_9_Fixacao_externa_media_4: string
  questao_9_Fixacao_externa_media_5: string
  questao_9_Fixacao_externa_media_6: string
  questao_9_Fixacao_externa_media_7: string
  questao_9_Fixacao_externa_media_8: string
  questao_9_Fixacao_externa_media_9: string
  questao_9_Grande_fixacao_externa_1: boolean
  questao_9_Grande_fixacao_externa_2: string
  questao_9_Grande_fixacao_externa_3: string
  questao_9_Grande_fixacao_externa_4: string
  questao_9_Grande_fixacao_externa_5: string
  questao_9_Grande_fixacao_externa_6: string
  questao_9_Grande_fixacao_externa_7: string
  questao_9_Grande_fixacao_externa_8: string
  questao_9_Grande_fixacao_externa_9: string
  questao_9_Mini_fixacao_externa_1: boolean
  questao_9_Mini_fixacao_externa_2: string
  questao_9_Mini_fixacao_externa_3: string
  questao_9_Mini_fixacao_externa_4: string
  questao_9_Mini_fixacao_externa_5: string
  questao_9_Mini_fixacao_externa_6: string
  questao_9_Mini_fixacao_externa_7: string
  questao_9_Mini_fixacao_externa_8: string
  questao_9_Mini_fixacao_externa_9: string
  questao_9_Parafusos_extremidades_inferiores_1: boolean
  questao_9_Parafusos_extremidades_inferiores_2: string
  questao_9_Parafusos_extremidades_inferiores_3: string
  questao_9_Parafusos_extremidades_inferiores_4: string
  questao_9_Parafusos_extremidades_inferiores_5: string
  questao_9_Parafusos_extremidades_inferiores_6: string
  questao_9_Parafusos_extremidades_inferiores_7: string
  questao_9_Parafusos_extremidades_inferiores_8: string
  questao_9_Parafusos_extremidades_inferiores_9: string
  questao_9_Parafusos_extremidades_superiores_1: boolean
  questao_9_Parafusos_extremidades_superiores_2: string
  questao_9_Parafusos_extremidades_superiores_3: string
  questao_9_Parafusos_extremidades_superiores_4: string
  questao_9_Parafusos_extremidades_superiores_5: string
  questao_9_Parafusos_extremidades_superiores_6: string
  questao_9_Parafusos_extremidades_superiores_7: string
  questao_9_Parafusos_extremidades_superiores_8: string
  questao_9_Parafusos_extremidades_superiores_9: string
  questao_9_Parafusos_grandes_e_canulados_1: boolean
  questao_9_Parafusos_grandes_e_canulados_2: string
  questao_9_Parafusos_grandes_e_canulados_3: string
  questao_9_Parafusos_grandes_e_canulados_4: string
  questao_9_Parafusos_grandes_e_canulados_5: string
  questao_9_Parafusos_grandes_e_canulados_6: string
  questao_9_Parafusos_grandes_e_canulados_7: string
  questao_9_Parafusos_grandes_e_canulados_8: string
  questao_9_Parafusos_grandes_e_canulados_9: string
  questao_9_Parafusos_para_quadril_ou_pelvis_1: boolean
  questao_9_Parafusos_para_quadril_ou_pelvis_2: string
  questao_9_Parafusos_para_quadril_ou_pelvis_3: string
  questao_9_Parafusos_para_quadril_ou_pelvis_4: string
  questao_9_Parafusos_para_quadril_ou_pelvis_5: string
  questao_9_Parafusos_para_quadril_ou_pelvis_6: string
  questao_9_Parafusos_para_quadril_ou_pelvis_7: string
  questao_9_Parafusos_para_quadril_ou_pelvis_8: string
  questao_9_Parafusos_para_quadril_ou_pelvis_9: string
  questao_9_Pequena_fixacao_externa_1: boolean
  questao_9_Pequena_fixacao_externa_2: string
  questao_9_Pequena_fixacao_externa_3: string
  questao_9_Pequena_fixacao_externa_4: string
  questao_9_Pequena_fixacao_externa_5: string
  questao_9_Pequena_fixacao_externa_6: string
  questao_9_Pequena_fixacao_externa_7: string
  questao_9_Pequena_fixacao_externa_8: string
  questao_9_Pequena_fixacao_externa_9: string
  questao_9_Pino_intramedular_femoral_1: boolean
  questao_9_Pino_intramedular_femoral_2: string
  questao_9_Pino_intramedular_femoral_3: string
  questao_9_Pino_intramedular_femoral_4: string
  questao_9_Pino_intramedular_femoral_5: string
  questao_9_Pino_intramedular_femoral_6: string
  questao_9_Pino_intramedular_femoral_7: string
  questao_9_Pino_intramedular_femoral_8: string
  questao_9_Pino_intramedular_femoral_9: string
  questao_9_Pinos_intramedulares_acetabulares_1: boolean
  questao_9_Pinos_intramedulares_acetabulares_2: string
  questao_9_Pinos_intramedulares_acetabulares_3: string
  questao_9_Pinos_intramedulares_acetabulares_4: string
  questao_9_Pinos_intramedulares_acetabulares_5: string
  questao_9_Pinos_intramedulares_acetabulares_6: string
  questao_9_Pinos_intramedulares_acetabulares_7: string
  questao_9_Pinos_intramedulares_acetabulares_8: string
  questao_9_Pinos_intramedulares_acetabulares_9: string
  questao_9_Pinos_intramedulares_tibiais_1: boolean
  questao_9_Pinos_intramedulares_tibiais_2: string
  questao_9_Pinos_intramedulares_tibiais_3: string
  questao_9_Pinos_intramedulares_tibiais_4: string
  questao_9_Pinos_intramedulares_tibiais_5: string
  questao_9_Pinos_intramedulares_tibiais_6: string
  questao_9_Pinos_intramedulares_tibiais_7: string
  questao_9_Pinos_intramedulares_tibiais_8: string
  questao_9_Pinos_intramedulares_tibiais_9: string
  questao_9_Pinos_intramedulares_umeral_1: boolean
  questao_9_Pinos_intramedulares_umeral_2: string
  questao_9_Pinos_intramedulares_umeral_3: string
  questao_9_Pinos_intramedulares_umeral_4: string
  questao_9_Pinos_intramedulares_umeral_5: string
  questao_9_Pinos_intramedulares_umeral_6: string
  questao_9_Pinos_intramedulares_umeral_7: string
  questao_9_Pinos_intramedulares_umeral_8: string
  questao_9_Pinos_intramedulares_umeral_9: string
  questao_9_Placas_extremidades_inferiores_1: boolean
  questao_9_Placas_extremidades_inferiores_2: string
  questao_9_Placas_extremidades_inferiores_3: string
  questao_9_Placas_extremidades_inferiores_4: string
  questao_9_Placas_extremidades_inferiores_5: string
  questao_9_Placas_extremidades_inferiores_6: string
  questao_9_Placas_extremidades_inferiores_7: string
  questao_9_Placas_extremidades_inferiores_8: string
  questao_9_Placas_extremidades_inferiores_9: string
  questao_9_Placas_extremidades_superiores_1: boolean
  questao_9_Placas_extremidades_superiores_2: string
  questao_9_Placas_extremidades_superiores_3: string
  questao_9_Placas_extremidades_superiores_4: string
  questao_9_Placas_extremidades_superiores_5: string
  questao_9_Placas_extremidades_superiores_6: string
  questao_9_Placas_extremidades_superiores_7: string
  questao_9_Placas_extremidades_superiores_8: string
  questao_9_Placas_extremidades_superiores_9: string
  questao_9_Placas_para_quadril_ou_pelvis_1: boolean
  questao_9_Placas_para_quadril_ou_pelvis_2: string
  questao_9_Placas_para_quadril_ou_pelvis_3: string
  questao_9_Placas_para_quadril_ou_pelvis_4: string
  questao_9_Placas_para_quadril_ou_pelvis_5: string
  questao_9_Placas_para_quadril_ou_pelvis_6: string
  questao_9_Placas_para_quadril_ou_pelvis_7: string
  questao_9_Placas_para_quadril_ou_pelvis_8: string
  questao_9_Placas_para_quadril_ou_pelvis_9: string
  questao_9_parafusos_pequenos_e_canulados_1: boolean
  questao_9_parafusos_pequenos_e_canulados_2: string
  questao_9_parafusos_pequenos_e_canulados_3: string
  questao_9_parafusos_pequenos_e_canulados_4: string
  questao_9_parafusos_pequenos_e_canulados_5: string
  questao_9_parafusos_pequenos_e_canulados_6: string
  questao_9_parafusos_pequenos_e_canulados_7: string
  questao_9_parafusos_pequenos_e_canulados_8: string
  questao_9_parafusos_pequenos_e_canulados_9: string
  questao_10_Fixacao_externa_media_10: string
  questao_10_Grande_fixacao_externa_10: string
  questao_10_Mini_fixacao_externa_10: string
  questao_10_Parafusos_extremidades_inferiores_10: string
  questao_10_Parafusos_extremidades_superiores_10: string
  questao_10_Parafusos_grandes_e_canulados_10: string
  questao_10_Parafusos_para_quadril_ou_pelvis_10: string
  questao_10_Pequena_fixacao_externa_10: string
  questao_10_Pino_intramedular_femoral_10: string
  questao_10_Pinos_intramedulares_acetabulares_10: string
  questao_10_Pinos_intramedulares_tibiais_10: string
  questao_10_Pinos_intramedulares_umeral_10: string
  questao_10_Placas_extremidades_inferiores_10: string
  questao_10_Placas_extremidades_superiores_10: string
  questao_10_Placas_para_quadril_ou_pelvis_10: string
  questao_10_parafusos_pequenos_e_canulados_10: string
  questao_10_particular: string
  questao_10_seguro_privado: string
  questao_10_sus: string
  questao_11: string
  questao_11_1: string
  questao_12: string
  questao_12_1: string
  questao_12_2: string
  questao_12_3: string
  questao_13: string
  questao_13_1: string
  questao_13_2: string
  questao_13_3: string
  questao_13_4: string
  questao_14: string
  questao_15: string
  questao_16: string
  comentario: string
  telefoneString: string
}